### ISSUE TITLE
Shriekers

### ISSUE THREAD

**Issue by epiktechno** [AzureDoom/Aftershock#2]
some odd reason, shriekers eating rotten flesh(and most likely other foods that induce status effects) crashes the game, but it gives no reason why the game crashes

another thing: shrieker's birth animation has a sort of "cooldown" between each food item, so if they eat one item it plays fine... but if they eat another right after the animation doesn't play

**Comment by AzureDoom** [comment]
Can you please provide a crash log for the crash? 

As for the animation, this is known and is still being worked on.

**Comment by LatentDesire1** [comment]
idk about rotten flesh, but a crash happened after one at some rabbit meat.
https://paste.ee/p/OIFHp

Is repeatable.
